# Generated by Django 2.2.5 on 2019-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
