# Generated by Django 2.2.5 on 2019-09-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactmessage_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='datetime',
            new_name='time',
        ),
    ]
