# Generated by Django 2.2.5 on 2019-09-29 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190928_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='time',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
