# Generated by Django 2.2.5 on 2019-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190928_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(editable=False, max_length=2047),
        ),
    ]
