# Generated by Django 2.2.5 on 2019-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190928_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2047)),
                ('local_link', models.URLField(blank=True, help_text='Link to the running project.')),
                ('source_link', models.URLField(blank=True, help_text="Link to the project's source code.")),
            ],
        ),
    ]
