# Generated by Django 2.2.5 on 2019-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The time this model was created at.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(editable=False, help_text='The email provided by the user.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(editable=False, help_text='The message provided by the user.', max_length=2047),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(editable=False, help_text='The name provided by the user.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The last time this model was modified at.'),
        ),
    ]
