# Generated by Django 2.2.5 on 2019-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190930_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image representing the project', upload_to='')),
                ('name', models.CharField(help_text='The name or title of the project.', max_length=100)),
                ('description', models.TextField(help_text='A description of the project.', max_length=2047)),
                ('local_link', models.URLField(blank=True, help_text='Link to the running project.')),
                ('source_link', models.URLField(blank=True, help_text="Link to the project's source code.")),
            ],
        ),
    ]
