# Generated by Django 3.0.4 on 2020-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191024_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this model was created at.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time this model was modified at.')),
                ('title', models.CharField(help_text='Blog title.', max_length=255)),
                ('content', models.TextField(help_text='Markdown and/or HTML blog content.', max_length=35565)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
