# Generated by Django 3.0.4 on 2020-04-04 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200404_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pulished_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date this blog was published on.'),
            preserve_default=False,
        ),
    ]
