# Generated by Django 3.0.4 on 2020-04-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_blog_pulished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pulished_at',
            new_name='published_at',
        ),
    ]
