# Generated by Django 3.0.4 on 2020-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200404_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='writeup_link',
            field=models.URLField(blank=True, help_text='Link to writeup or blog about project.'),
        ),
    ]
