# Generated by Django 3.0.7 on 2020-07-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_project_writeup_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
